search_keywords_list = [
# 'inurl: 外車王',
# 'inurl: gaisha oh',
# 'inurl: 外車　査定',
# 'inurl: 外車　買取',
# 'inurl: 外車　売却',
# 'inurl: 王　外車',
# 'inurl: 輸入車　王',
# 'inurl: 輸入車　査定',
# 'inurl: 輸入車　買取',
# 'inurl: 輸入車　売却',
# 'inurl: 旧車王',
# 'inurl: qsha oh',
# 'inurl: 旧車　査定',
# 'inurl: 旧車　買取',
# 'inurl: 旧車　売却',
# 'inurl: 王　旧車',
# 'inurl: Q車　買取',
# 'inurl: Q車　査定',
# 'inurl: Q車　売却',
# 'inurl: Q社　買取',
# 'inurl: Q社　査定',
# 'inurl: Q社　売却',
# 'inurl: 改車王',
# 'inurl: 改造車　査定',
# 'inurl: 改造車　買取',
# 'inurl: 改造車　売却',
# 'inurl: 王　査定',
# 'inurl: 王　買取',
'inurl: 王　売却',
'inurl: ラボ　車　買取',
'inurl: ラボ買取',
'inurl: スポーツカーラボ',
'inurl: スーパーカーラボ',
'inurl: ガレージカレントキャンプ',
'inurl: バスラボ',
'inurl: トラックラボ',
'inurl: フードトラックラボ',
'inurl: スバラボ',
'inurl: レクラボ',
'inurl: SUVラボ',
'inurl: ミニバンラボ',
'inurl: 軽自動車ラボ',
'inurl: オープンカーラボ',
'inurl: セダンラボ',
'inurl: アルヴェルラボ',
'inurl: リペア王',
'inurl: 事故車王',
'inurl: 福祉車王',
'inurl: 故障車王',
'inurl: スカイ王',
'inurl: スポ車王',
'inurl: 輸入車鑑定士',
'inurl: 中古車鑑定士',
'inurl: 自動車文化遺産',
'inurl: クルマスカウト',
'inurl: 外車',
'inurl: 旧車',
'inurl: 輸入車',
'inurl: アメ車',
'inurl: ドイツ車',
'inurl: イタリア車'
    ]